from typing import List, Dict
from backend.agents.course_idea_generator import CourseIdeaGenerator
from backend.orchestrator.synthetic_intelligence import SyntheticIntelligence
from backend.services.pricing.calculator import PricingCalculator
from backend.models.course import Course
from backend.database import SessionLocal

class CourseGenerator:
    """Orchestrates creation of multiple courses in batch."""
    
    def __init__(self):
        self.idea_gen = CourseIdeaGenerator()
        self.course_creator = SyntheticIntelligence()
    
    async def generate_free_intro_courses(self, count: int = 10) -> List[Dict]:
        """Generate short (1‑module) free courses that introduce full paid courses."""
        categories = ['trending', 'traditional', 'rare', 'dying']
        ideas_per_cat = max(1, count // len(categories))
        all_courses = []
        
        for cat in categories:
            ideas = self.idea_gen.generate_ideas(cat, count=ideas_per_cat, is_free=True)
            for idea in ideas:
                # Create a simple 1‑module blueprint
                blueprint = {
                    "title": idea['title'],
                    "description": idea['description'],
                    "category": cat,
                    "modules": [{
                        "title": "Introduction & First Steps",
                        "objectives": ["Understand the basics", "Try a mini‑project"]
                    }],
                    "is_free": True
                }
                # Use existing AI pipeline but force short mode
                course = await self.course_creator.create_course(blueprint, short_mode=True)
                course['price_zar'] = 0
                course['price_usd'] = 0
                # Save to DB
                db_course = self._save_course_to_db(course)
                all_courses.append(db_course)
        return all_courses
    
    async def generate_paid_courses(self, count: int = 30) -> List[Dict]:
        """Generate full‑length paid courses with 4‑8 modules each."""
        categories = ['trending', 'traditional', 'rare', 'dying']
        # Weight: trending & dying get more courses
        weights = {'trending': 0.4, 'traditional': 0.2, 'rare': 0.2, 'dying': 0.2}
        all_courses = []
        
        for cat, weight in weights.items():
            cat_count = int(count * weight)
            ideas = self.idea_gen.generate_ideas(cat, count=cat_count, is_free=False)
            
            for idea in ideas:
                # Determine number of modules based on complexity (4-8)
                import random
                module_count = random.randint(4, 8)
                
                blueprint = {
                    "title": idea['title'],
                    "description": idea['description'],
                    "category": cat,
                    "target_audience": idea.get('target_audience', 'everyone'),
                    "modules": self._generate_module_titles(module_count, idea['title']),
                    "is_free": False
                }
                # Generate full course
                course = await self.course_creator.create_course(blueprint, short_mode=False)
                # Add pricing
                prices = PricingCalculator.calculate(module_count, is_free=False)
                course['price_zar'] = prices['price_zar']
                course['price_usd'] = prices['price_usd']
                # Save to DB
                db_course = self._save_course_to_db(course)
                all_courses.append(db_course)
        return all_courses
    
    def _save_course_to_db(self, course_data: dict):
        """Persist course, modules, lessons to database."""
        db = SessionLocal()
        try:
            course = Course(
                title=course_data['title'],
                description=course_data['description'],
                category=course_data['category'],
                is_free=course_data.get('is_free', False),
                price_zar=course_data.get('price_zar'),
                price_usd=course_data.get('price_usd'),
                intro_to_course_id=course_data.get('intro_to_course_id')
            )
            db.add(course)
            db.commit()
            db.refresh(course)
            return course
        finally:
            db.close()
    
    def _generate_module_titles(self, count: int, course_title: str):
        """Helper to create plausible module titles."""
        # In practice, this would be generated by StrategicAgent
        return [{"title": f"Module {i+1}: {self._module_name(i)}"} for i in range(count)]
    
    def _module_name(self, i):
        names = ["Foundations", "Core Skills", "Practice", "Advanced Techniques", "Real‑World Projects", "Mastery", "Troubleshooting", "Next Steps"]
        return names[i] if i < len(names) else f"Level {i+1}"
